# Generated by Django 4.1.7 on 2023-04-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_store_alter_food_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='djangoapp.menu'),
        ),
    ]
